import type { CampEvent, Facility } from "./types.ts";

/**
 * SYNTHETIC demonstration data for Nearby Care.
 *
 * Every facility and camp below is FICTIONAL. They are shaped like real
 * ABDM HFR / NHM / PM-JAY records so the UI and adapters can be exercised, but
 * they must be labelled "Demonstration data — not real facilities" in the UI
 * and must never be presented as live, open, or bed-available.
 *
 * Coordinates are placed around a fictional Meghalaya cluster to match the
 * existing dashboard's "Mawlynnong cluster" demo setting.
 */

const REGION_CENTER = { lat: 25.1986, lng: 91.8785 };

export const SYNTHETIC_FACILITIES: Facility[] = [
  {
    id: "F-DEMO-001",
    name: "Mawlynnong District Hospital (demo)",
    type: "hospital",
    coordinates: { lat: 25.2001, lng: 91.8802, accuracyMeters: 10, source: "gps" },
    address: "District Hospital Road, Mawlynnong",
    villageCode: "MWL",
    phone: "+913612000001",
    capabilities: {
      emergency: true,
      icu: true,
      oxygen: true,
      paediatrics: true,
      maternity: true,
      surgery: true,
      ambulance: true,
      pharmacy: true,
      mental_health: true,
      diagnostics: true,
    },
    schemes: ["ayushman", "pmjay", "abdm_hfr", "state_nhm"],
    openNow: true,
    verification: "verified",
    verificationSource: "ABDM Health Facility Registry (demo)",
    verifiedAt: "2026-07-01T00:00:00Z",
    expiresAt: "2027-07-01T00:00:00Z",
    externalId: "HFR-DEMO-001",
    sourceUrl: "https://facility.hfr.abdm.gov.in (demo)",
    lastFetchedAt: "2026-08-01T00:00:00Z",
  },
  {
    id: "F-DEMO-002",
    name: "Pynursla CHC (demo)",
    type: "chc",
    coordinates: { lat: 25.1842, lng: 91.9023, accuracyMeters: 15, source: "gps" },
    address: "Community Health Centre, Pynursla",
    villageCode: "PYN",
    phone: "+913612000002",
    capabilities: {
      emergency: true,
      icu: false,
      oxygen: true,
      paediatrics: true,
      maternity: true,
      surgery: false,
      ambulance: true,
      pharmacy: true,
      mental_health: false,
      diagnostics: true,
    },
    schemes: ["state_nhm", "pmjay"],
    openNow: true,
    verification: "verified",
    verificationSource: "State NHM directory (demo)",
    verifiedAt: "2026-06-15T00:00:00Z",
    externalId: "CHC-DEMO-002",
    sourceUrl: "https://nhm.meg[.]gov[.]in (demo)",
    lastFetchedAt: "2026-07-20T00:00:00Z",
  },
  {
    id: "F-DEMO-003",
    name: "North Ridge PHC (demo)",
    type: "phc",
    coordinates: { lat: 25.221, lng: 91.861, accuracyMeters: 20, source: "gps" },
    address: "Primary Health Centre, North Ridge",
    villageCode: "NRT",
    phone: "+913612000003",
    capabilities: {
      emergency: false,
      icu: false,
      oxygen: false,
      paediatrics: true,
      maternity: true,
      surgery: false,
      ambulance: false,
      pharmacy: true,
      mental_health: false,
      diagnostics: false,
    },
    schemes: ["state_nhm"],
    openNow: true,
    verification: "verified",
    verificationSource: "District health administration (demo)",
    verifiedAt: "2026-05-10T00:00:00Z",
    externalId: "PHC-DEMO-003",
    sourceUrl: "https://meg[.]gov[.]in/district (demo)",
    lastFetchedAt: "2026-06-01T00:00:00Z",
  },
  {
    id: "F-DEMO-004",
    name: "Mawlynnong Arogya Mandir (demo)",
    type: "aam",
    coordinates: { lat: 25.197, lng: 91.874, accuracyMeters: 12, source: "gps" },
    address: "Ayushman Arogya Mandir, Mawlynnong",
    villageCode: "MWL",
    capabilities: {
      emergency: false,
      icu: false,
      oxygen: false,
      paediatrics: false,
      maternity: false,
      surgery: false,
      ambulance: false,
      pharmacy: false,
      mental_health: false,
      diagnostics: true,
    },
    schemes: ["ayushman", "abdm_hfr"],
    openNow: true,
    verification: "verified",
    verificationSource: "ABDM HFR (demo)",
    verifiedAt: "2026-07-12T00:00:00Z",
    externalId: "AAM-DEMO-004",
    sourceUrl: "https://facility.hfr.abdm.gov.in (demo)",
    lastFetchedAt: "2026-08-05T00:00:00Z",
  },
  {
    id: "F-DEMO-005",
    name: "Riverside Clinic (demo, unverified)",
    type: "clinic",
    coordinates: { lat: 25.176, lng: 91.889, accuracyMeters: 18, source: "gps" },
    address: "Near river market, Pynursla",
    villageCode: "PYN",
    capabilities: {
      emergency: true,
      icu: false,
      oxygen: false,
      paediatrics: false,
      maternity: false,
      surgery: false,
      ambulance: false,
      pharmacy: true,
      mental_health: false,
      diagnostics: false,
    },
    schemes: ["none"],
    openNow: undefined,
    verification: "unverified",
    verificationSource: "OpenStreetMap (supplemental)",
    externalId: "OSM-DEMO-005",
    sourceUrl: "https://www.openstreetmap.org (demo)",
    lastFetchedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "F-DEMO-006",
    name: "Hillside Pharmacy (demo)",
    type: "pharmacy",
    coordinates: { lat: 25.205, lng: 91.872, accuracyMeters: 14, source: "gps" },
    address: "Main bazaar, Mawlynnong",
    villageCode: "MWL",
    phone: "+913612000006",
    capabilities: {
      emergency: false,
      icu: false,
      oxygen: false,
      paediatrics: false,
      maternity: false,
      surgery: false,
      ambulance: false,
      pharmacy: true,
      mental_health: false,
      diagnostics: false,
    },
    schemes: ["none"],
    openNow: true,
    verification: "verified",
    verificationSource: "State NHM directory (demo)",
    verifiedAt: "2026-07-01T00:00:00Z",
    externalId: "PHARM-DEMO-006",
    sourceUrl: "https://nhm.meg[.]gov[.]in (demo)",
    lastFetchedAt: "2026-07-25T00:00:00Z",
  },
];

export const SYNTHETIC_CAMPS: CampEvent[] = [
  {
    id: "C-DEMO-001",
    title: "Weekly maternal & child health camp (demo)",
    organiser: "District NHM",
    source: "State NHM feed (demo)",
    services: ["antenatal check", "immunisation", "nutrition counselling"],
    eligibility: "Pregnant women and children under 5",
    start: "2026-08-22T09:00:00Z",
    end: "2026-08-22T14:00:00Z",
    recurrence: "weekly: Wednesday",
    venue: "Arogya Mandir, Mawlynnong",
    coordinates: { lat: 25.197, lng: 91.874, accuracyMeters: 12, source: "manual" },
    contact: "+913612000099",
    verification: "verified",
    lastVerifiedAt: "2026-08-18T00:00:00Z",
    cancelled: false,
    validityEnd: "2026-12-31T00:00:00Z",
  },
  {
    id: "C-DEMO-002",
    title: "MMU mobile clinic visit (demo)",
    organiser: "Mobile Medical Unit, East Khasi Hills",
    source: "MMU schedule (demo)",
    services: ["general medicine", "diagnostics", "tele-consult"],
    eligibility: "All residents",
    start: "2026-08-23T10:00:00Z",
    end: "2026-08-23T13:00:00Z",
    recurrence: "biweekly: Thursday",
    venue: "Pynursla CHC ground",
    coordinates: { lat: 25.1842, lng: 91.9023, accuracyMeters: 15, source: "manual" },
    contact: "+913612000098",
    verification: "verified",
    lastVerifiedAt: "2026-08-17T00:00:00Z",
    cancelled: false,
    validityEnd: "2026-11-30T00:00:00Z",
  },
  {
    id: "C-DEMO-003",
    title: "Expired eye-screening camp (demo — should be hidden)",
    organiser: "NGO (demo)",
    source: "Community upload (demo)",
    services: ["eye screening"],
    eligibility: "All residents",
    start: "2026-01-10T09:00:00Z",
    end: "2026-01-10T16:00:00Z",
    venue: "Village hall, North Ridge",
    coordinates: { lat: 25.221, lng: 91.861, accuracyMeters: 20, source: "manual" },
    verification: "unverified",
    cancelled: false,
    validityEnd: "2026-01-10T23:59:00Z",
  },
];

export { REGION_CENTER };

/** Camps whose validity window has passed or that are cancelled are hidden. */
export function activeCamps(now: Date = new Date()): CampEvent[] {
  return SYNTHETIC_CAMPS.filter(
    (c) => !c.cancelled && new Date(c.validityEnd).getTime() >= now.getTime(),
  );
}
